name: Send Email Report

on:
  schedule:
    # Runs every day at 6 AM PST; adjust cron expression as needed
    - cron: '0 14 * * *'
  workflow_dispatch:  # Allows manual triggering
  push:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Install dependencies from requirements.txt
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run email report script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          source venv/bin/activate
          python src/main.py
