name: Send Email Report

on:
  schedule:
    # Runs every day at 6AM, 12PM, 6PM, and 10PM PST; adjust cron expression as needed
    - cron: '0 6,12,18,22 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Install dependencies from requirements.txt
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run email report script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          source venv/bin/activate
          python src/main.py

      - name: Upload log as artifact
        if: always()  
        uses: actions/upload-artifact@v4
        with:
          name: captains_log
          path: app.log
